services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/root/catkin_ws/src
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    network_mode: host
    container_name: ros_dev_container
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: bash -c "source /opt/ros/noetic/setup.bash"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: roslaunch gem_gazebo gem_gazebo_rviz.launch velodyne_points:="true"
    container_name: ros_app
    depends_on:
      - dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  # gazebo:
  #   image: osrf/ros:noetic-desktop-full
  #   # build: .
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - ROS_MASTER_URI=http://ros_dev_container:11311
  #     - ROS_HOSTNAME=gazebo
  #   network_mode: host
  #   container_name: gazebo
  #   privileged: true
  #   devices:
  #     - /dev/dri:/dev/dri
  #   volumes:
  #     - .:/root/catkin_ws/src
  #   command: tail -f /dev/null
    # command: bash -c "source devel/setup.bash && roslaunch gem_gazebo gem_gazebo_rviz.launch velodyne_points:="true""

  # rviz:
  #   image: osrf/ros:noetic-desktop-full
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - ROS_MASTER_URI=http://ros_dev_container:11311
  #     - ROS_HOSTNAME=rviz
  #   network_mode: host
  #   container_name: rviz
  #   privileged: true
  #   # runtime: nvidia  # Only needed if you're using NVIDIA GPUs
  #   devices:
  #     - /dev/dri:/dev/dri
  #   volumes:
  #     - .:/root/catkin_ws/src
  #   command: bash -c "source /opt/ros/noetic/setup.bash && rviz"

  # polaris_gem_e2:
  #   image: osrf/ros:noetic-desktop-full
  #   environment:
  #     - DISPLAY=:1
  #     - QT_X11_NO_MITSHM=1
  #   network_mode: host
  #   container_name: polaris_gem_e2
  #   privileged: true
  #   volumes:
  #     - .:/root/catkin_ws/src
  #   command: tail -f /dev/null