services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/root/catkin_ws/src
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    network_mode: host
    container_name: ros_dev_container
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: bash -c "source /opt/ros/noetic/setup.bash"
